cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: <ACCESS-KEY>
      secret-key: <SECRET-KEY>
    end-point:
            uri: <END-POINT>
    stack:
      auto: false

server:
  port: 8083

